services:
  - type: web
    name: auto-v-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MPESA_ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    plan: starter
    healthCheckPath: /api/health
