"""
Utils Package
"""

from app.utils.decorators import (
    rate_limit,
    require_auth,
    require_role,
    log_request,
    handle_errors,
    retry_on_failure,
    measure_performance,
    cache_response,
    public_endpoint,
    protected_endpoint,
    admin_endpoint,
    get_rate_limit_status,
    RateLimiter,
)

from app.utils.logger import (
    setup_logger,
    get_logger,
    logger_middleware,
    log_context,
    get_default_logger,
    JSONFormatter,
    ColoredFormatter,
    LoggerFactory,
)

from app.utils.validators import (
    validate_email,
    normalize_email,
    validate_phone,
    normalize_phone,
    validate_vin,
    validate_vin_format,
    extract_vin_from_text,
    get_vin_country,
    validate_odometer,
    validate_odometer_trend,
    validate_amount,
    validate_positive_amount,
    validate_date,
    validate_date_range,
    parse_date,
    format_date,
    validate_kenya_id,
    validate_kra_pin,
    validate_plate,
    Validators,
    EmailModel,
    PhoneModel,
    VinModel,
    AmountModel,
)

__all__ = [
    # Decorators
    "rate_limit",
    "require_auth",
    "require_role",
    "log_request",
    "handle_errors",
    "retry_on_failure",
    "measure_performance",
    "cache_response",
    "public_endpoint",
    "protected_endpoint",
    "admin_endpoint",
    "get_rate_limit_status",
    "RateLimiter",
    
    # Logger
    "setup_logger",
    "get_logger",
    "logger_middleware",
    "log_context",
    "get_default_logger",
    "JSONFormatter",
    "ColoredFormatter",
    "LoggerFactory",
    
    # Validators
    "validate_email",
    "normalize_email",
    "validate_phone",
    "normalize_phone",
    "validate_vin",
    "validate_vin_format",
    "extract_vin_from_text",
    "get_vin_country",
    "validate_odometer",
    "validate_odometer_trend",
    "validate_amount",
    "validate_positive_amount",
    "validate_date",
    "validate_date_range",
    "parse_date",
    "format_date",
    "validate_kenya_id",
    "validate_kra_pin",
    "validate_plate",
    "Validators",
    "EmailModel",
    "PhoneModel",
    "VinModel",
    "AmountModel",
]
